FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Alwan App



## getInit [/getInit]
### Getting Beginning Data[GET]

+ Response 202 (application/json)

    + Headers

            Location: /getInit

    + Body

                {
                    "cityList":     [
                        {
                            "CityID": 12,
                            "GermanName": "ggggg",
                            "ArabicName": "بببببب"
                        },
                        {
                            "CityID": 12,
                            "GermanName": "ggggg",
                            "ArabicName": "بببببب"
                        }
                    ],
                   "languageList":  [
                        {
                            "ID": 12,
                            "Language": "بابابابابابااب"
                        },
                        {
                            "ID": 12,
                            "Language": "باباباباباباب"
                        }
                    ],
                    "mailReceivers": [
                        {
                            "ID": 12,
                            "Email": "بابابابابابااب"
                        },
                        {
                            "ID": 12,
                            "Email": "باباباباباباب"
                        }
                    ],
                    "mailCC": [
                        {
                            "ID": 12,
                            "Email": "باباباباباباباب"
                        },
                        {
                            "ID": 12,
                            "Email": "باباباباباباباب"
                        }
                    ]
                }
                
                
## getFullData [/getFullData/{LanguageID}]
### Getting The Full Data Related to the Language [GET]

+ Response 202 (application/json)

    + Headers

            Location: /getFullData/2

    + Body   
                
                
            {
                "activities": [
                    {
                      "id": 7,
                      "title": "فيغت",
                      "location": "غعت",
                      "details": "غفت",
                      "onDate": "4/1/2015",
                      "image": "635654939651575605.jpg",
                      "galleryUrl": "فيغت"
                    },
                    {
                      "id": 9,
                      "title": "ggg",
                      "location": "ggg",
                      "details": "ggg",
                      "onDate": "4/13/2015",
                      "image": "635657324214026240.jpg",
                      "galleryUrl": "ggg"
                    },
                    {
                      "id": 10,
                      "title": "f",
                      "location": "fff",
                      "details": "f",
                      "onDate": "4/6/2015",
                      "image": "635657323398604722.jpg",
                      "galleryUrl": "f"
                    }
                ],
                "flashes": [
                    {
                      "id": 1,
                      "title": "erg",
                      "file": "635657334565110206.wav"
                    },
                    {
                      "id": 12,
                      "title": "ghh",
                      "file": "635657330475471426.mp4"
                    }
                ],
                "releases": [
                    {
                      "id": 10,
                      "title": "rttg",
                      "details": "hhh",
                      "image": "635657362167254147.png",
                      "rFile": "635657362028571226.pdf"
                    },
                    {
                      "id": 14,
                      "title": "vvvv",
                      "details": "vvvv",
                      "image": "635660014417168613.png",
                      "rFile": "635660014205868972.pdf"
                    }
                ],
                "donationData": {
                    "id": 0,
                    "text": null,
                    "donateUrl": null
                },
                "contactData": {
                    "id": 0,
                    "address": null,
                    "phone": null,
                    "fax": null,
                    "email": null,
                    "website": null
                }
            }
            
            
## getPrayerTimes [/getPrayerTimes/{yearNumber}/{CityID}]
### Getting Prayer Times [GET]

+ Response 202 (application/json)

    + Headers

            Location: /getPrayerTimes/2015/9

    + Body


                {
                    "id": 12,,
                    "day": "4/13/2015",
                    "dawn": "12:00 am",
                    "sunrise": "12:00 am",
                    "noon": "12:00 am",
                    "afternoon": "12:00 am",
                    "sunset": "12:00 am",
                    "night": "12:00 am"
                },
                {
                    "id": 12,
                    "day": "4/13/2015",
                    "dawn": "12:00 am",
                    "sunrise": "12:00 am",
                    "noon": "12:00 am",
                    "afternoon": "12:00 am",
                    "sunset": "12:00 am",
                    "night": "12:00 am"
                }

                
                
                