FORMAT: 1A

# Alwan App

## getInit [/api/getInit]
### Getting Beginning Data[GET]

+ Response 202 (application/json)

    + Headers

            Location: api/getInit

    + Body

                {
                    "cityList":     [
                        {
                            "cityId": 12,
                            "germanName": "ggggg",
                            "arabicName": "بببببب"
                        },
                        {
                            "cityId": 12,
                            "germanName": "ggggg",
                            "arabicName": "بببببب"
                        }
                    ],
                   "languageList":  [
                        {
                            "languageId": 12,
                            "language": "بابابابابابااب"
                        },
                        {
                            "languageId": 12,
                            "language": "باباباباباباب"
                        }
                    ],
                    "mailReceivers": [
                        {
                            "id": 12,
                            "email": "بابابابابابااب"
                        },
                        {
                            "id": 12,
                            "email": "باباباباباباب"
                        }
                    ],
                    "mailCC": [
                        {
                            "id": 12,
                            "email": "باباباباباباباب"
                        },
                        {
                            "id": 12,
                            "email": "باباباباباباباب"
                        }
                    ]
                }
                
                
## getFullData [/api/getFullData/{languageId}]

This method has the following attributes:

+ languageId

+ Parameters
    + languageId (required, int`) ... languageId in the form of an integer --> 1, 2 ...

### Getting The Full Data Related to the Language [GET]

+ Response 202 (application/json)

    + Headers

            Location: api/getFullData/2

    + Body   
                
                
            {
                "activities": [
                    {
                      "id": 7,
                      "title": "فيغت",
                      "location": "غعت",
                      "details": "غفت",
                      "onDate": "4/1/2015",
                      "image": "635654939651575605.jpg",
                      "galleryUrl": "فيغت"
                    },
                    {
                      "id": 9,
                      "title": "ggg",
                      "location": "ggg",
                      "details": "ggg",
                      "onDate": "4/13/2015",
                      "image": "635657324214026240.jpg",
                      "galleryUrl": "ggg"
                    },
                    {
                      "id": 10,
                      "title": "f",
                      "location": "fff",
                      "details": "f",
                      "onDate": "4/6/2015",
                      "image": "635657323398604722.jpg",
                      "galleryUrl": "f"
                    }
                ],
                "flashes": [
                    {
                      "id": 1,
                      "title": "erg",
                      "file": "635657334565110206.wav"
                    },
                    {
                      "id": 12,
                      "title": "ghh",
                      "file": "635657330475471426.mp4"
                    }
                ],
                "releases": [
                    {
                      "id": 10,
                      "title": "rttg",
                      "details": "hhh",
                      "image": "635657362167254147.png",
                      "rFile": "635657362028571226.pdf"
                    },
                    {
                      "id": 14,
                      "title": "vvvv",
                      "details": "vvvv",
                      "image": "635660014417168613.png",
                      "rFile": "635660014205868972.pdf"
                    }
                ],
                "donationData": {
                    "id": 0,
                    "text": "Bitte unterstützen\nSie unsere vitale Arbeit\nIhr Geld macht den",
                    "donateUrl": "https://www.google.com.lb/?gws_rd=cr"
                    },
                "contactData": {
                    "id": 0,
                    "address": "https://www.google.com.lb/?gws_rd=cr,ssl&ei=OYAuVeSJM46y7Qai4IHAAg",
                    "phone": "9090900",
                    "fax": "808008080",
                    "email": "https://www.google.com.lb/?gws_rd=cr,ssl&ei=OYAuVeSJM46y7Qai4IHAAg",
                    "website": "https://www.google.com.lb/?gws_rd=cr,ssl&ei=OYAuVeSJM46y7Qai4IHAAg"
                }
            }
        
        
## getPrayerTimes [/api/getPrayerTimes/{yearNumber}/{cityId}/{monthId}]

This method has the following attributes:

+ yearNumber
+ cityId
+ monthId

+ Parameters
    + yearNumber (required, string`) ... the yearNumber in the form of a string --> "2015"
    + cityId (required, int`) ... cityId in the form of an integer --> 1, 2 ...
    + monthId (required, int`) ... monthId in the form of an integer --> 2, 12, ...

### Getting Prayer Times [GET]

+ Response 202 (application/json)

    + Headers

            Location: api/getPrayerTimes/2015/9/5

    + Body

            [
                {
                    "id": 12,
                    "day": "23/05/2015",
                    "dawn": "12:00 am",
                    "sunrise": "12:00 am",
                    "noon": "12:00 am",
                    "afternoon": "12:00 am",
                    "sunset": "12:00 am",
                    "night": "12:00 am"
                },
                {
                    "id": 12,
                    "day": "26/3/2015",
                    "dawn": "12:00 am",
                    "sunrise": "12:00 am",
                    "noon": "12:00 am",
                    "afternoon": "12:00 am",
                    "sunset": "12:00 am",
                    "night": "12:00 am"
                }
            ]
            
            
            
## getRamadanTimes [/api/getRamadanTimes/{cityId}]

This method has the following attributes:

+ cityId

+ Parameters
    + cityId (required, int`) ... cityId in the form of an integer --> 1, 2 ...

### Getting Ramadan Times [GET]

+ Response 202 (application/json)

    + Headers

            Location: api/getRamadanTimes/9

    + Body


                {
                    "id": 454
                    "ramadanDay": 31
                    "alimseek": "06 : 22"
                    "dawn": "06 : 22"
                    "sunrise": "08 : 14"
                    "noon": "12 : 49"
                    "afternoon": "15 : 01"
                    "sunset": "17 : 51"
                    "night": "19 : 00"
                    "day": "6/18/2015"
                },
                {
                    "id": 454
                    "ramadanDay": 31
                    "alimseek": "06 : 22"
                    "dawn": "06 : 22"
                    "sunrise": "08 : 14"
                    "noon": "12 : 49"
                    "afternoon": "15 : 01"
                    "sunset": "17 : 51"
                    "night": "19 : 00"
                    "day": "6/18/2015"
                }

## tokenRegister [/api/tokenRegister]
### Registering the device token [POST]

                 
+ Request (application/json)

            {   "deviceToken": "123456ergerg", 
                "deviceType": "ios"}

+ Response 202 (application/json)

    + Headers

            Location: api/tokenRegister

    + Body

            {
                "success": true,
                "error": 0,
                "message": "",
                "data": ""
            }

                 
                 
            
                